// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using icolsaProyecto.Data;

#nullable disable

namespace icolsaProyecto.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251109235739_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("icolsaProyecto.Models.Categoria", b =>
                {
                    b.Property<int>("IDCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDCategoria"));

                    b.Property<string>("Nombre_Categoria")
                        .HasColumnType("longtext");

                    b.HasKey("IDCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Cliente", b =>
                {
                    b.Property<int>("IDCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDCliente"));

                    b.Property<string>("Apellido_Cliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Correo_Cliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion_Cliente")
                        .HasColumnType("longtext");

                    b.Property<string>("NIT_Cliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre_Cliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono_Cliente")
                        .HasColumnType("longtext");

                    b.HasKey("IDCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("icolsaProyecto.Models.DetallePedido", b =>
                {
                    b.Property<int>("IDDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDetallePedido"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("IDPedido")
                        .HasColumnType("int");

                    b.Property<int?>("IDProducto")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IDDetallePedido");

                    b.HasIndex("IDPedido");

                    b.HasIndex("IDProducto");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("icolsaProyecto.Models.EstadoPago", b =>
                {
                    b.Property<int>("IDEstadoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDEstadoPago"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IDEstadoPago");

                    b.ToTable("EstadosPago");
                });

            modelBuilder.Entity("icolsaProyecto.Models.HistorialInventarioSaldo", b =>
                {
                    b.Property<int>("IDInventarioSaldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDInventarioSaldo"));

                    b.Property<DateTime?>("Fecha_Actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IDProducto")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoIDProducto")
                        .HasColumnType("int");

                    b.Property<int?>("Saldo_Actual")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .HasColumnType("longtext");

                    b.HasKey("IDInventarioSaldo");

                    b.HasIndex("IDProducto");

                    b.HasIndex("ProductoIDProducto");

                    b.ToTable("HistorialInventarioSaldos");
                });

            modelBuilder.Entity("icolsaProyecto.Models.MetodoPago", b =>
                {
                    b.Property<int>("IDMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDMetodoPago"));

                    b.Property<string>("NombreMetodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IDMetodoPago");

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Pago", b =>
                {
                    b.Property<int>("IDPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDPago"));

                    b.Property<int?>("ClienteIDCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Pago")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IDEstadoPago")
                        .HasColumnType("int");

                    b.Property<int>("IDMetodoPago")
                        .HasColumnType("int");

                    b.Property<int>("IDPedido")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto_Pago")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PedidoIDPedido")
                        .HasColumnType("int");

                    b.HasKey("IDPago");

                    b.HasIndex("ClienteIDCliente");

                    b.HasIndex("IDEstadoPago");

                    b.HasIndex("IDMetodoPago");

                    b.HasIndex("IDPedido");

                    b.HasIndex("PedidoIDPedido");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Pedido", b =>
                {
                    b.Property<int>("IDPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDPedido"));

                    b.Property<int?>("Cantidad_Pedido")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteIDCliente")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_Pedido")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IDCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IDProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPago_Pedido")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("UsuarioIDUsuario")
                        .HasColumnType("int");

                    b.HasKey("IDPedido");

                    b.HasIndex("ClienteIDCliente");

                    b.HasIndex("IDCliente");

                    b.HasIndex("IDProducto");

                    b.HasIndex("IDUsuario");

                    b.HasIndex("UsuarioIDUsuario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Producto", b =>
                {
                    b.Property<int>("IDProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDProducto"));

                    b.Property<int?>("CategoriaIDCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Codigo_Producto")
                        .HasColumnType("longtext");

                    b.Property<int?>("IDCategoria")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre_Producto")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PrecioUnitario_Producto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("Stock_Producto")
                        .HasColumnType("int");

                    b.HasKey("IDProducto");

                    b.HasIndex("CategoriaIDCategoria");

                    b.HasIndex("IDCategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Reporte", b =>
                {
                    b.Property<int>("IDReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDReporte"));

                    b.Property<DateTime?>("Fecha_Reporte")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_Reporte")
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioIDUsuario")
                        .HasColumnType("int");

                    b.HasKey("IDReporte");

                    b.HasIndex("IDUsuario");

                    b.HasIndex("UsuarioIDUsuario");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDUsuario"));

                    b.Property<string>("Contrasena_Usuario")
                        .HasColumnType("longtext");

                    b.Property<string>("Correo_Usuario")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre_Usuario")
                        .HasColumnType("longtext");

                    b.Property<string>("Rol_Usuario")
                        .HasColumnType("longtext");

                    b.HasKey("IDUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("icolsaProyecto.Models.DetallePedido", b =>
                {
                    b.HasOne("icolsaProyecto.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IDPedido")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("icolsaProyecto.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IDProducto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("icolsaProyecto.Models.HistorialInventarioSaldo", b =>
                {
                    b.HasOne("icolsaProyecto.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IDProducto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("icolsaProyecto.Models.Producto", null)
                        .WithMany("HistorialInventarioSaldos")
                        .HasForeignKey("ProductoIDProducto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Pago", b =>
                {
                    b.HasOne("icolsaProyecto.Models.Cliente", null)
                        .WithMany("Pagos")
                        .HasForeignKey("ClienteIDCliente");

                    b.HasOne("icolsaProyecto.Models.EstadoPago", "EstadoPago")
                        .WithMany()
                        .HasForeignKey("IDEstadoPago")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("icolsaProyecto.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("IDMetodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("icolsaProyecto.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IDPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("icolsaProyecto.Models.Pedido", null)
                        .WithMany("Pagos")
                        .HasForeignKey("PedidoIDPedido");

                    b.Navigation("EstadoPago");

                    b.Navigation("MetodoPago");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Pedido", b =>
                {
                    b.HasOne("icolsaProyecto.Models.Cliente", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteIDCliente");

                    b.HasOne("icolsaProyecto.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("icolsaProyecto.Models.Producto", "Producto")
                        .WithMany("Pedidos")
                        .HasForeignKey("IDProducto");

                    b.HasOne("icolsaProyecto.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("icolsaProyecto.Models.Usuario", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioIDUsuario");

                    b.Navigation("Cliente");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Producto", b =>
                {
                    b.HasOne("icolsaProyecto.Models.Categoria", null)
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaIDCategoria");

                    b.HasOne("icolsaProyecto.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IDCategoria")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Reporte", b =>
                {
                    b.HasOne("icolsaProyecto.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("icolsaProyecto.Models.Usuario", null)
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioIDUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Cliente", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Producto", b =>
                {
                    b.Navigation("HistorialInventarioSaldos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("icolsaProyecto.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
